services:
  eseed:
    build: .
    image: eseed
    hostname: eseed
    container_name: eseed
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./env:/app/env
      - ./log:/app/log
    depends_on:
      - mongo
      - redis
      - minio

  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678

  redis:
    image: redis
    hostname: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --requirepass 12345678

  minio:
    image: minio/minio
    hostname: minio
    container_name: minio
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 12345678
    command: server /data --console-address ":9090"

volumes:
  mongo_data:
  redis_data:
  minio_data:
